pud: fix openwrt glibc compilation
When compiling pud with glibc it will result in

  error: #warning _FORTIFY_SOURCE requires compiling with optimization
   (-O) [-Werror=cpp]
  #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^~~~~~~
  cc1: all warnings being treated as errors

To compile pud with glibc again we remove Werror.

Signed-off-by: Nick Hainke <vincent@systemli.org>